apiVersion: v1
kind: Secret
metadata:
  name: rocketchat-ssl
  namespace: kube-public
data:
    tls.crt: ""
    tls.key: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: rocketchat-registry-qjw-hj-key
  namespace: kube-public
data:
    .dockerconfigjson: $(base64 -w 0 ~/.docker/config.json)
type: kubernetes.io/dockerconfigjson
