apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mongo
 namespace: kube-public
spec:
 serviceName: "mongo"
 replicas: 3
 template:
   metadata:
     labels:
       role: mongo
       environment: test
   spec:
     terminationGracePeriodSeconds: 10
     imagePullSecrets:
        - name: rocketchat-registry-qjw-hj-key
     containers:
       - name: mongo
         image: registry.apps.k8s.qjw.hj/mongo:4.0
         command:
           - mongod
           - "--bind_ip_all"
           - "--replSet"
           - rs0
           - "--smallfiles"
           - "--noprealloc"
         ports:
           - containerPort: 27017
         volumeMounts:
           - name: mongo-persistent-storage
             mountPath: /data/db
       - name: mongo-sidecar
         image: registry.apps.k8s.qjw.hj/cvallance/mongo-k8s-sidecar
         env:
           - name: MONGO_SIDECAR_POD_LABELS
             value: "role=mongo,environment=test"
           - name: KUBERNETES_MONGO_SERVICE_NAME
             value: "mongo"
 volumeClaimTemplates:
 - metadata:
     name: mongo-persistent-storage
     annotations:
       volume.beta.kubernetes.io/storage-class: "storageclass-default"
   spec:
     accessModes: [ "ReadWriteOnce" ]
     resources:
       requests:
         storage: 100Gi
